language: ruby

rvm:
  - 2.3.1  

before_script:
  - gem install bundler
  - bundle install

script:
  - bundle exec rake db:setup
  - rails s
  
notifications:
  email:
    recipients:
      - nicacionetobsb@gmail.com
